### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by gjtorikian** [ajaxorg/ace-builds#10]
I can finally talk about Releases: https://github.com/blog/1547-release-your-software

Seems like this repository should be removed. I never liked the idea of having two storage locations for Ace. It would make more sense to tag and update releases in the main Ace repository. 

You can drag in a zip/tarball of the built files with each Release. An API is forthcoming, so the process could even be automated soon.

**Comment by mryellow** [comment]
For those landing here. The actual code is at https://github.com/ajaxorg/ace
