### ISSUE TITLE
Provide mirror worker to the build

### ISSUE THREAD

**Issue by roonyh** [ajaxorg/ace-builds#100]
I am trying to use ace-builds src-noconflict to create a custom worker. I am using instructions from: https://github.com/ajaxorg/ace/wiki/Syntax-validation

But `var Mirror = ace.require("ace/worker/mirror").Mirror;` returns `undefined`. Seems its not `ace.defined`. Could you please provide it? Or suggest a workaround?

**Comment by roonyh** [comment]
My related SO question: http://stackoverflow.com/questions/42465341/how-to-use-mirror-worker-for-ace-editor-with-ace-builds

**Comment by yossely** [comment]
#### Hi @roonyh!

I have the same issue as you, I'm trying to create a custom worker to validate the syntax to the mode _c\_cpp_  (`C` programming language)... I'm currently using the npm package [brace](https://www.npmjs.com/package/brace) and `Mirror` always returns undefined...

Could you solve your issue?

**Comment by roonyh** [comment]
I ended up taking the suggestion from this answer https://stackoverflow.com/a/42632568/1150725

Sorry I didn't reply earlier @yossely :( this notification must have slipped through.

We don't use ace anymore, switched to monaco. So I can't really give a detailed answer atm :/
