### ISSUE TITLE
Removed files still included in builds

### ISSUE THREAD

**Issue by tqc** [ajaxorg/ace-builds#104]
The build script may need a clenup step added, as ace-builds includes several files that are no longer created with a clean build - For example ext/chromevox.js, which was removed with https://github.com/ajaxorg/ace/pull/3024 due to CLA issues.

There are also some like snippets/mipsassembler.js where I wasn't able to find the original source in the history at all.

**Comment by nightwing** [comment]
fixed in 1.3.2
