### ISSUE TITLE
Ace is huge

### ISSUE THREAD

**Issue by victorbstan** [ajaxorg/ace-builds#11]
Hi, perhaps I'm not sure what I'm supposed to do, but is there an easy way to figure out what the minimum requirements are, in terms of files and their organization, for a subset of the functionality that Ace provides? 

As an example, if I only care about syntax highlighting for CSS, and one theme, what are the minimum files I can use, without having my app serve all the JS and CSS that just slows down load times?

**Comment by ZachSaucier** [comment]
@nightwing Is there a modern equivalent of `ext-options.js` for `CTRL`+`+` functionality?

**Comment by Canopee** [comment]
Bonjour,
Après 7 riches années passées au sein de l’agence Canopée, j’ai décidé de prendre mon envol pour une autre destination professionnelle.
C’était un plaisir de collaborer ensemble durant ces années au sein de l’agence. L’équipe de Canopée prend bien sûr le relai pour poursuivre l’aventure.
Pour toutes vos questions techniques, de maintenance et de suivi de dossier, vous pouvez maintenant vous adresser à Coline Ducasse.
Elle est joignable par téléphone  04 90 98 79 39 ou à l'adresse coline.ducasse@canopee.cc

Je vous souhaite de passer une agréable journée.
Bien cordialement

Alexis Esteves

**Comment by nightwing** [comment]
@ZachSaucier what do you mean by `CTRL++ functionality`, ext-options.js is still the same, if you are asking for a new feature please create a new issue or use one of Ace google groups.

**Comment by ZachSaucier** [comment]
@nightwing The link above for ext-options.js is a 404 and I don't see it in the GitHub repo under src

CTRL+ functionality is zooming in on text

**Comment by nightwing** [comment]
Oh right, it should have been https://github.com/ajaxorg/ace-builds/blob/master/src/ext-settings_menu.js.
by default ace leaves handling of zoom to the browser.
If you want to only change font size of the editor, you can use something like https://github.com/ajaxorg/ace/blob/674902d89dd2ab7f0104fa89b1aa409a7ddc40d9/demo/kitchen-sink/demo.js#L185-L205

```js
editor.commands.addCommands([{{
    name: "increaseFontSize",
    bindKey: "Ctrl-=|Ctrl-+",
    exec: function(editor) {
        var size = parseInt(editor.getFontSize(), 10) || 12;
        editor.setFontSize(size + 1);
    }
}, {
    name: "decreaseFontSize",
    bindKey: "Ctrl+-|Ctrl-_",
    exec: function(editor) {
        var size = parseInt(editor.getFontSize(), 10) || 12;
        editor.setFontSize(Math.max(size - 1 || 1));
    }
}, {
    name: "resetFontSize",
    bindKey: "Ctrl+0|Ctrl-Numpad0",
    exec: function(editor) {
        editor.setFontSize(12);
    }
}]);
```

**Comment by ZachSaucier** [comment]
@nightwing Thanks a lot!
