### ISSUE TITLE
Please set a description to this repo

### ISSUE THREAD

**Issue by 304NotModified** [ajaxorg/ace-builds#111]
Please set a description:

![image](https://user-images.githubusercontent.com/5808377/28260452-665b456a-6adb-11e7-88c3-ea9bee7338b9.png)

It's already a bit confusing that there are 2 repos IMO

**Comment by nightwing** [comment]
This repo contains a packaged version of ace, for people who do not use require.js

I've added a description now, let me know if you have a suggestion for a better one.

**Comment by 304NotModified** [comment]
Looks good, thanks!
