### ISSUE TITLE
How to import ace-build to a vue based project

### ISSUE THREAD

**Issue by kaixin** [ajaxorg/ace-builds#116]
I run "npm install ace-builds --save". I've got ace-builds in my node_modules folder. I tried to import it to my project by "import AceBuilds from 'ace-builds'", but the UI console has error saying "Module not found: Error: Can't resolve 'ace-builds'". How should I use the ace-builds in my vue based project properly?

**Comment by nightwing** [comment]
try using brace https://github.com/thlorenz/brace, or add the script without import, ace-builds does not support browserify/webpack for now.

**Comment by nightwing** [comment]
```js
import ace from "ace-builds"
```
should work with the newly released 1.3.2 version.

to enable automatic loading of modes, install file-loader webpack plugin and use
```js
import "ace/webpack-resolver";
```
see demo at https://github.com/ajaxorg/ace/blob/master/demo/webpack/demo.js

**Comment by akontsevich** [comment]
@nightwing is it possible to use ace-builds with browserify now? brace is very outdated.

**Comment by nightwing** [comment]
ace-builds can be used with webpack.

For it to work with browserify we need some way to get urls to some scripts that are not included in the main bundle, but i couldn't find anything like that for browserify. 
Do you know if browserify has some related functionality that i am missing?

**Comment by akontsevich** [comment]
> ace-builds can be used with webpack.

Browserify is much simpler and easier to use. Will need some time to learn webpack.

> Do you know if browserify has some related functionality that i am missing?

Not sure, beginner in these technologies.

**Comment by nightwing** [comment]
How do you handle images and other assets that are loaded from url?

If you know the url from which your site is loaded and can get ace-builds/src-noconflict folder deployed, use 
```js
ace.config.set("basePath", "https://<...>/ace-builds/src-noconflict")
```

to load modes from that path.

**Comment by JeSuisUnCaillou** [comment]
> ```js
> import ace from "ace-builds"
> ```
> 
> ```js
> import "ace/webpack-resolver"
> ```

This answer from @nightwing is still relevant today 👍
