### ISSUE TITLE
package 31.01.18 doesn't contain latest code

### ISSUE THREAD

**Issue by NeilFraser** [ajaxorg/ace-builds#123]
This is probably just my misunderstanding of your build strategy.

I submitted a patch 17 days ago here:
https://github.com/ajaxorg/ace/commit/ecae928c011253f288583f170609841014e59fe9
It fixes some syntax errors that trip up compilers, but the most visible change is fixing the typo "unknow Class:"

A couple of days ago this rebuild landed:
https://github.com/ajaxorg/ace-builds/commit/fb2286eba4a1d7a95e32fca2187d8a4409e6885c
It recompiles these two files:
https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/worker-xml.js
https://github.com/ajaxorg/ace-builds/blob/master/src-min-noconflict/worker-xml.js
Both these files still contain the compiler syntax error and the old typo "unknow Class:".

Did I submit my patch to the wrong place?  Or is your build strategy slower than I'm expecting?

Thanks!

**Comment by nightwing** [comment]
Sorry about the delay. Currently we only update this repository only when publishing new versions, usually about once a month. We are planning to add a ci job to update this repo automatically, but it will take some time.

I'll publish a new version this weekend

**Comment by NeilFraser** [comment]
Cool, no problem.  I just wanted to make sure it was somewhere in the pipeline and that I hadn't screwed up my patch location.  No hurry on our end.  Thanks again.

**Comment by NeilFraser** [comment]
Ping?

**Comment by nightwing** [comment]
published 1.3.2, sorry for the delay
