### ISSUE TITLE
Adding custom modes

### ISSUE THREAD

**Issue by agduncan94** [ajaxorg/ace-builds#131]
Is it possible to use custom modes? I have created a new mode for highlighting and have tested it with https://ace.c9.io/tool/mode_creator.html, but was wondering what steps to take to use it in a project. Do the modes have to be added ahead of time into the npm package?

**Comment by nightwing** [comment]
To use ace-builds directly, you need to create a file in a format similar to https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/mode-json.js#L257.
If the custom mode is for a commonly used language, you can submit the mode to ace repo instead.

**Comment by agduncan94** [comment]
Thank you I got it working using that as the basis for my custom mode. I'll link it [here](https://github.com/dockstore/dockstore-ui2/blob/6f65c665419ff44ac8c49c4955ac9c6f2b5475f3/src/app/shared/grammars/custom-grammars.js) in case someone in the future is interested in getting custom modes working, might be a good starting point (it is a bit hacky so will need some cleanup, but it at least works)

**Comment by cedrickabongo** [comment]
> Thank you I got it working using that as the basis for my custom mode. I'll link it [here](https://github.com/dockstore/dockstore-ui2/blob/6f65c665419ff44ac8c49c4955ac9c6f2b5475f3/src/app/shared/grammars/custom-grammars.js) in case someone in the future is interested in getting custom modes working, might be a good starting point (it is a bit hacky so will need some cleanup, but it at least works)

this worked perfectly for me. thank you very much.
