### ISSUE TITLE
Needed multiple editors

### ISSUE THREAD

**Issue by nicerinno** [ajaxorg/ace-builds#132]
Hello!
I needed 3 editors at once, in one page. I'm doing a live editor where I can edit HTML, CSS and Javascript.
What's happening is that when the page loads, I can only click on the last editor I've placed on the page, I cant access the others, only if I click on the line number and then use the arrow keys.
Do you have any idea on how to fix this?
Cheers!

**Comment by agduncan94** [comment]
Are you able to jsfiddle of this or link to your code or provide some relevant code? It might be specific to how you are using it in your project.

**Comment by nicerinno** [comment]
I just found out and it was an easy fix. I changed their div's position, and then they worked. I think there was some div overlap
