### ISSUE TITLE
Blob workaround

### ISSUE THREAD

**Issue by KyooMario** [ajaxorg/ace-builds#148]
Hello ACE,

Your solution works with a blob but in the platform Salesforce it is rejected with the message: Refused to create a worker from 'blob' because it violates the following Content Security Policy directive: "script-src 'self' 

Can you provide a workaround?

Kind regards,
Mario

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3862/files added support for loading the worker script directly by setting `ace.config.set("loadWorkerFromBlob", false)`
