### ISSUE TITLE
Various JS strict warnings when running Ace 1.4.3 in the Thunderbird HTML window

### ISSUE THREAD

**Issue by jorgk3** [ajaxorg/ace-builds#149]
I've just integrated Ace 1.4.3 into the my Thunderbird add-on using "src-min-noconflict".

In a debug build of Thunderbird I see heap of JS warnings in the console window (see below). During very light testing I didn't see any functional problems.

JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property 1
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ext-language_tools.js, line 1: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "row"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "$highlightRuleConfig"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "type"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "foldingRules"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "$foldMode"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "allowBoldFonts"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "$defaultHandler"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "session"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "regExp"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "$enableMultiselect"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "inMultiSelectMode"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "startAutocomplete"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property 0
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "-1"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "$tagHighlight"
JavaScript strict warning: chrome://thunderhtmledit/content/ace/mode-html.js, line 1: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://thunderhtmledit/content/ace/ace.js, line 1: ReferenceError: reference to undefined property "token"

**Comment by nightwing** [comment]
This warnings were present in previous versions too, and do not seem to cause any problem other than noise in the console. Also some of them are hard to solve because they are produced by the minifier.
