### ISSUE TITLE
Use SPDX identifier for license

### ISSUE THREAD

**Issue by NeoDobby** [ajaxorg/ace-builds#150]
The license name specified in package.json ("BSD") is not a valid SPDX license identifier (see https://docs.npmjs.com/files/package.json#license and https://spdx.org/licenses/).

NPM packages like license-checker (https://www.npmjs.com/package/license-checker) rely on the license being specified with a valid SPDX identifier.

The license seems to be BSD-3-Clause, so this should be noted int the package.json. 

Is it possible to also have this fixed for version 1.2.8?

**Comment by nightwing** [comment]
Updated license on the master branch. 
Unfortunately i do not know of any way to update old releases either on github or on npm.
