### ISSUE TITLE
EjsMode start new line

### ISSUE THREAD

**Issue by ahmad-dci** [ajaxorg/ace-builds#155]
Hello,
thank you for this nice plugin.
I tried to use Ace with EjsMode. and the editor add every time a new line to the begining of the code and also 4 tabs before the first line.
`var templateEditor = ace.edit("templateContentArea");
    var EjsMode = ace.require("ace/mode/ejs").Mode;
    templateEditor.session.setMode(new EjsMode());`

![issue_ice](https://user-images.githubusercontent.com/40862364/62426155-85c9c300-b6e1-11e9-8232-1f959557e458.png)

**Comment by nightwing** [comment]
sounds like you are doing something like 

```ejs
<div id=templateContentArea>
     ${code}
</div>
```

which adds additional whitespace, instead of that, do:
```ejs
<div id=templateContentArea>${code}</div>
```

**Comment by jenylion** [comment]
thanks for fast reply 
that solved the problem but ${} is shown in the editor like a part of the edited code

**Comment by jenylion** [comment]
Sorry for that you were right I should write the element in one line like this
<div id=templateContentArea>code</div>
