### ISSUE TITLE
为什么我的javascript错误语法没有提示

### ISSUE THREAD

**Issue by zxc0312** [ajaxorg/ace-builds#156]
![image](https://user-images.githubusercontent.com/46018796/63563970-c5275900-c595-11e9-97c3-55598c656a25.png)

**Comment by zxc0312** [comment]
![image](https://user-images.githubusercontent.com/46018796/63670195-9ff14f80-c80e-11e9-9784-184683d5daf0.png)
前台加载，应该怎么解决？

**Comment by mctang719** [comment]
把aceeditor的代码发出来？
