### ISSUE TITLE
ace.edit can't find div #javascript-editor in Angular Material elements

### ISSUE THREAD

**Issue by PriyathamKommula** [ajaxorg/ace-builds#160]
I'm trying to create a JavaScript editor inside an AngularMaterialModule and ace.edit('editor') fails to find the #javascript-editor inside the element

```
<mat-tab-group>
  <mat-tab label="Editor">
    <h4>Custom Editor</h4>
    <div id="javascript-editor" style="height: 300px;"></div>
  </mat-tab>
</mat-tab-group>
```

```
import { Component, OnInit } from '@angular/core';

import * as ace from 'brace';
import 'brace/mode/javascript';
import 'brace/theme/monokai';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements OnInit {
  ngOnInit() {
    const editor = ace.edit('javascript-editor');
    editor.getSession().setMode('ace/mode/javascript');
    editor.setTheme('ace/theme/monokai');
  }
}

```

The same code when placed outside the mat-tab in a div works fine.

I have a code sample at [StackBlitz](https://stackblitz.com/edit/angular-jkhzsw)

I'm using angular6

**Comment by nightwing** [comment]
`ace.edit("idString")` is a shortcut for `ace.edit(document.getElementById("idString"))`, in your example the element with id "javascript-editor" is not present on the page, either find the element and pass it directly to `ace.edit` or call  `editor = ace.edit(null)`, and then add the `editor.container` element to the position in the dom tree you want.
