### ISSUE TITLE
Inject custom span in editor

### ISSUE THREAD

**Issue by daleixo-gocontact** [ajaxorg/ace-builds#168]
Hello

I am using ace for some time now and really loving it. Great job.

I have on requirement that is to insert one custom variable on the editor. Say i want to put something like:

`var x = §{my_custom_variable_fancy_name}`

But ${my_custom_variable} should have attributes so then when i parse the text i make some replacements.

For example, suppose the following HTML for previous the example

`<div class="ace...">var x = <span class="color: red" data-prop="prop" data-id="23">my_custom_variable_fancy_name</span></div>`

It would translate on my backend to something like

`var x = 23[prop]`

I hope i could explain my self better.

Is it possible?

**Comment by nightwing** [comment]
There is no way to add html to the editor because it would not be possible to keep general html data during the editing. You probably can keep values of attributes outside the text and restore them from `my_custom_variable_fancy_name`
