### ISSUE TITLE
[webpack] - breaking change of webpack-resolver with file-loader 5.0.0?

### ISSUE THREAD

**Issue by dlangerenken** [ajaxorg/ace-builds#170]
Since file-loader 5.0.0, it will now by default export to es-modules, making ace-builds generate a wrong URL in the webpack-resolver (instead of simply the path, it will try to use an {esmodule: true, ...} object.) and therefore triggers a request to http://localhost:8080/[object%20Module]

See https://github.com/webpack-contrib/file-loader/blob/master/CHANGELOG.md

Now I could be wrong and it's entirely a setup issue on my end, but I verified that it works fine with 4.3.0 and breaks when switching to 5.0.0. Not sure how to fix it without a breaking change - ideally using file-loader?esModule=false./pathtoscripts.

With 4.3.0 I get:
![image](https://user-images.githubusercontent.com/3457885/72231996-52823e80-3573-11ea-9d56-9924282f10ea.png)

With 5.0.0+ I see:
![image](https://user-images.githubusercontent.com/3457885/72232083-d3d9d100-3573-11ea-8bc3-3d8a4dbe8105.png)

**Comment by nightwing** [comment]
@dlangerenken thanks for the suggestion! `?esModule=false` works both with the old and the new versions of fileloader  https://github.com/ajaxorg/ace/pull/4151

**Comment by dlangerenken** [comment]
Thanks @nightwing  - I guess I used the wrong repository for filing the suggestion. Much appreciated that you applied a fix so fast!
