### ISSUE TITLE
[enhancement] Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [ajaxorg/ace-builds#20]
#### Hey, maintainer(s) of ajaxorg/ace-builds!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, *224* of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `ajaxorg/ace-builds` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "ajaxorg/ace-builds",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by Juice10** [comment]
:+1:

**Comment by dnauck** [comment]
+1 for adding bower.json

**Comment by tomsouthall** [comment]
+1

**Comment by varemenos** [comment]
:+1:

**Comment by antonshubin** [comment]
+1

**Comment by hackur** [comment]
+1

**Comment by veged** [comment]
:+1:

**Comment by beckyconning** [comment]
:+1:

**Comment by discordier** [comment]
:+1:

**Comment by mattvick** [comment]
+1

**Comment by frankmarineau** [comment]
+1

**Comment by m4rkmckenna** [comment]
:+1:

**Comment by R4wizard** [comment]
+1

**Comment by VytautasB** [comment]
+1

**Comment by BMartinos** [comment]
+1

**Comment by Qwol** [comment]
+1

**Comment by nightwing** [comment]
added in https://github.com/ajaxorg/ace-builds/pull/82
