### ISSUE TITLE
change cursor event calling everytime 

### ISSUE THREAD

**Issue by ajai06** [ajaxorg/ace-builds#200]
editor.getSelection().on('changeCursor');

this event calling every time(non-stopping) without keyboard click or mouse movement 

"ace-builds": "^1.4.12"
"@angular/cli": "^6.2.9"

**Comment by nightwing** [comment]
One possible cause is that something calls setValue or changes the selection, maybe something from angular integration.

Could you please share a demo page where this is happening? That would help to debug the issue.

**Comment by ajai06** [comment]
the purpose is integrating collaborating editing, for that we are using AceCollabExt from '@convergencelabs/ace-collab-ext' and socket.io 

`this.editor.getSelection().on('changeCursor', (data) => {
                var cursorData                  = {};
                cursorData['cur_position']  = this.editor.getCursorPosition();
                cursorData['cur_color']     = this.currentUserColor;
                cursorData['cur_uname']     = this.currentUserCollab;
            this.collabService.sendCursorData(cursorData);
        });`
        
        `settingCollab(){
        this.curMgr  = new AceCollabExt.AceMultiCursorManager(this.editor.getSession());
        this.selMgr  = new AceCollabExt.AceMultiSelectionManager(this.editor.getSession());
        this.radarView = new AceCollabExt.AceRadarView('target-radar-view', this.editor);
        }`


      // after fetching data
     `setCursorAce(data){
        //try catch : if id is already set
        // setting updated cursor with id
        try {
            this.curMgr._getCursor(data['cur_uname'].toLowerCase());
            this.curMgr.setCursor(data['cur_uname'].toLowerCase(), data['cur_position']);
        }
        catch(err) {
            this.curMgr.addCursor(data['cur_uname'].toLowerCase(), data['cur_uname'], data['cur_color'], data['cur_position']);
        }
    }`

**Comment by ajai06** [comment]
issue fixed.. accidentally calling one function two times. thanks
