### ISSUE TITLE
Customize comment format

### ISSUE THREAD

**Issue by ericuldall** [ajaxorg/ace-builds#202]
Currently using SCSS mode and when using the togglecomment feature it adds comments as `// comment`.
However I'd like to know if there's a way to configure that separately so we can use `/* comment */`

Is it possible to override this value at init time?

**Comment by nightwing** [comment]
This is handled in https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/text.js#L74, deleting lineCommentStart should work but it will also have the adverse effect that // will not be removed by togglecomment.
