### ISSUE TITLE
嗨，最新的react-ace构建出来的东西有问题，是ace-builds上周更新的问题导致的么？

### ISSUE THREAD

**Issue by xiayongtian** [ajaxorg/ace-builds#247]
项目打包之后在项目中进行引用，theme-textmate，mode-javascript，snippets/text，theme-monokai，这几个包引用不到

**Comment by xiayongtian** [comment]
2023-06-25 10:33:54打包还是能够正常引入的，之后就引入报错了

**Comment by Willix-IT** [comment]
Exactly the same problem here. No errors, but in the console the same errors as him appear

**Comment by JesseCHN** [comment]
+1

**Comment by nataliasver** [comment]
I got the same problem, but the project uses Angular. I tried using version 1.22.1, but not fully works. 
Adding some other configs, solved partially the problem, but still got a problem with the worker-javascript.
Waiting for the fix, to see if that solves it.
