### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by lcotonea** [ajaxorg/ace-builds#31]
It could be fine if your build was deployed on bower repository

**Comment by melnikaite** [comment]
Solanolabs raise error:
```
Post-install message from rails-assets-ace-builds:
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/ajaxorg/ace-builds
```

**Comment by kudos** [comment]
@nightwing I don't know what happened, but it's not on bower now.

> You search didn't return any results. Please try a different keyword.

**Comment by aguegu** [comment]
please register it on bower, it will make the implement much easier and gain many new users.

It is kinda a basic requirement for modern frontend libs.

**Comment by aguegu** [comment]
ace-build can be found on bower, cool.

```
bower install ace-builds
```

**Comment by cornerman** [comment]
Installing ace-builds via bower directly works, but the package is not listed in the bower index. See here for further discussions: https://github.com/webjars/webjars/issues/1051.
