### ISSUE TITLE
Update build?

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace-builds#51]
I see that ace-builds is updated about once per month but not on any particular set schedule.  Now that a bunch of fixes have been merged into master and are passing CI tests, it might be a good time to do another build.

**Comment by iDeBugger** [comment]
+1

**Comment by caizixian** [comment]
+1 To solve rust-lang/rust-by-example#429

**Comment by rmsmith** [comment]
+1 / ping; are `ace-builds` still a thing?

**Comment by cubiclesoft** [comment]
Gonna close this issue now.  New build available.
