### ISSUE TITLE
ACE&textarea?

### ISSUE THREAD

**Issue by dokxpi** [ajaxorg/ace-builds#55]
Hello,
sorry for my English ...

###### ACE, the problems in the implementation
I need syntax highlighting inside textarea
Prompt how to be in my case?
http://jsfiddle.net/dokxpi/9vp72onu/5/

**Comment by nightwing** [comment]
Make sure there is a div with id `editor` and that div is visible without ace
`ace.edit` will create editor of the same size as that div

If you don't want to specify height with css, use
```js
editor.setOptions({
    minLines: 30,
    maxLines: 30,
})
```
In your example `ace.edit("twee")` should work too
