### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dawsonbotsford** [ajaxorg/ace-builds#56]
The link [scrollable-page-demo](http://ajaxorg.github.com/ace-builds/scrollable-page.html) on the repo home's README is broken. There does not appear to be a file like that any longer in the source code.

**Comment by nightwing** [comment]
fixed in https://github.com/ajaxorg/ace-builds/commit/29ec29ebe8c9e9b27e5520ca72000d754d4da473
