### ISSUE TITLE
How do I disable line selection on gutter click in ACE editor?

### ISSUE THREAD

**Issue by squarePenguin** [ajaxorg/ace-builds#59]
I'm trying to disable all user interaction with the ace editor. I managed to stop most interactions with the following settings:

```
codeEditor.setReadOnly(true);
codeEditor.setHighlightActiveLine(false);
codeEditor.setHighlightGutterLine(false);
codeEditor.container.style.pointerEvents = "none";
codeEditor.renderer.$cursorLayer.element.style.opacity = 0;
```

However, while most of the interactivity is now disabled, mousedown events on the gutter still work. For example, when you click on a gutter line, it still selects the text on that line. Other events such as double click for select all or code folding also seem to work. You can check it here:
http://jsfiddle.net/squarePenguin/zhpms1mm/

I tried to remove listeners on the gutter, but nothing seems to work. This is everything I tried:

```
codeEditor.getSession().removeAllListeners("guttermousedown");
codeEditor.getSession().removeAllListeners("gutterclick");
codeEditor.getSession().removeAllListeners("gutterdblclick");
codeEditor.getSession().removeAllListeners("guttermousemove");
codeEditor.getSession().removeAllListeners("click");
codeEditor.getSession().removeAllListeners("mousedown");
```

Do you have any idea? Thank you for your patience!

**Comment by sevin7676** [comment]
This might help:
```javascript
//dont allow selection
editor.on('changeSelection', function(e) {
    editor.selection.setSelectionRange({
        start: {
            row: 0,
            column: 0
        },
        end: {
            row: 0,
            column: 0
        }
    });
});
//dont allow commands
editor.commands.on("exec", function(e) {
    e.preventDefault();
});
```

For fold widgets, you can simply disable them using the editors settings

**Comment by githubsheng** [comment]
this will disable the selection behavior.
`    editor.on("guttermousedown", function(e) {
        e.stop();
    });`
