### ISSUE TITLE
Not able to start the undo from a specific time or event

### ISSUE THREAD

**Issue by shashank02** [ajaxorg/ace-builds#62]
in my page i have 4 links, by clicking the each link iam displaying data in the editor. If user clicks first and fourth links and then he press   ctrl+Z  it is showing the first link data and then again clearing the editor to created position.

Can i solve this using "session.doc.setValue"

**Comment by nightwing** [comment]
you can use session.setValue which resets undomanager or use separate sessions for each link.

**Comment by shashank02** [comment]
Hi nightwing,
i have used session.setValue but it is not happening. And about the links, they are generated dynamically and they can be more than 100. 

Can you please help with this.

Thank you.

**Comment by shashank02** [comment]
Thank you for your support nightwing.

**Comment by nightwing** [comment]
I don't quite understand what are you trying to achieve, was the above description of the bug or of the desired behavior?

**Comment by shashank02** [comment]
Sorry for that, i have gone through the document and i tried some things they did not worked, so i thought it is a bug.

The main reason was, i am creating the editor every time but it is still giving the old data. Its my mistake any way thank you and sorry.

**Comment by nightwing** [comment]
It might be a bug, please show the code you are using, and describe the behavior you want to achieve. I would be happy to help, but i do not have enough information yet.
