### ISSUE TITLE
Bundling in one file

### ISSUE THREAD

**Issue by veged** [ajaxorg/ace-builds#66]
Is there any way to bundle ACE in one file? Right now setting particular theme or mode entail downloading of separate file. I try just join all those separate downloaded files, but it doesn't work.

**Comment by nightwing** [comment]
joining files with ace.js first then modes and themes you want should work. joining worker-* files is not possible, since they need to be loaded into a web worker

**Comment by veged** [comment]
ok, thnx

and can I change the path for `worker-*` files (since they are not near main code)?

**Comment by nightwing** [comment]
yes, use ace.config.set("workerPath", "path/to/base")
