### ISSUE TITLE
was src-min-noconflict uploaded properly?

### ISSUE THREAD

**Issue by mdinger** [ajaxorg/ace-builds#67]
[rustbyexample.com](http://rustbyexample.com/) was relying on the master branch of ace-builds and it suddenly broke in the last few day or two, but only for `src-min-noconflict`.  All the others work fine. The browser console just kept saying:

```javascript
// ReferenceError: ace is not defined
var editor = ace.edit("editor");
```

I tried the `editor.html` file to see if it worked and it seemed to work fine. Do you know where this might have come from? I'm just expecting it might have been a bad upload but it's inconsistent. If not, I can possibly try to get you a smaller testcase.

**Comment by mdinger** [comment]
If I open the `src-min-noconflict` `ace.js` file in the firefox debugger, use the "prettify source" command at the bottom left, and paste that into a text file, resave as `ace.js`, then firefox complains of an `SyntaxError: unterminated string literal` on line `539`. That line looks like:

```js
    var _ = '\t\n\v\f\r   ᠎             　  ﻿';
```

The codepoints inside the `''` were these:

```txt
'\\'
't'
'\\'
'n'
'\\'
'v'
'\\'
'f'
'\\'
'r'
' '
' '
'\u{1680}'
'\u{180e}'
'\u{2000}'
'\u{2001}'
'\u{2002}'
'\u{2003}'
'\u{2004}'
'\u{2005}'
'\u{2006}'
'\u{2007}'
'\u{2008}'
'\u{2009}'
'\u{200a}'
'\u{202f}'
'\u{205f}'
'\u{3000}'
'\u{2028}'
'\u{2029}'
'\u{feff}'
```

Making that string an empty string makes `ace.js` basically work sorta okay but then it complains about something else. I wonder if the compression utility or prettify or whatever you're using is acting up here?

**Comment by nightwing** [comment]
It was indeed broken
I've uploaded working version in https://github.com/ajaxorg/ace-builds/commit/b082bcb4bf2da27a8def3c438a33ebf0dffe5afe, and added a test to prevent such errors in the future.

**Comment by mdinger** [comment]
Thanks!
