### ISSUE TITLE
Scroll error on Chrome v46

### ISSUE THREAD

**Issue by ofc587a87** [ajaxorg/ace-builds#68]
Hi,

I have detected an error on ACE when it's used in an iframe. After clicking inside of the ace control, the focus go to the upper part of the iframe, scrolling up the page and focusing in the element outside the iframe.

The code is working on chrome v45 (we have some non-updated computers). Also, the code works if it's not inside an iframe.

the code inside the iframe it's almost the same that the used in the tutorial:

> `<textarea id="cuerpo" name='cuerpo' cols='80' rows='40' class="html" style="display:none;">{CUERPO}</textarea>`
> `<div id="editor"></div>`
> 
> [...]
> 
> `$(document).ready(function() {`
>  `document.getElementById("editor").innerHTML =           document.getElementById("cuerpo").innerHTML.trim();`
> 
> `   editor = ace.edit("editor");`
> `   editor.setTheme("ace/theme/chrome");`
> `   editor.getSession().setMode("ace/mode/html");`
> `}`

**Comment by nightwing** [comment]
Could you please show an example of a page where this happens
I couldn't reproduce the issue with http://plnkr.co/edit/QqdOFlVBeRguhtWZ0SfB?p=preview

**Comment by ofc587a87** [comment]
I have reproduced it, and while doing so i have detected the problem:

http://plnkr.co/edit/uHYY98nX8xFdCUg69t4S?p=preview

Inside the iframe there are tabs (hidden/shown divs) and the tab link includes an href to '#' and an onclick event to execute the tab change.

Clicking on the ace component after changing tabs, with the iframe appointing to '#' scrolls the iframe to to top.

Removing the href to '#' resolves the issue. Anyway, there is a problem with the focus event. it's a rare case, of course, but it's there.

Thanks!

**Comment by nightwing** [comment]
Thanks for the update. 
The same thing happens without ace http://plnkr.co/edit/dRFCICTNSl3V0uSu04xR?p=preview, so we can't do anything about it, unfortunately.
Please try reporting the issue to https://code.google.com/p/chromium/issues/list

**Comment by ofc587a87** [comment]
I'll open an issuse at google site, so this ticket can be closed as is not related to the Ace.

Thank you for your support!
