### ISSUE TITLE
The file will become empty, when I press 'ctrl-z'.

### ISSUE THREAD

**Issue by StriverBoy** [ajaxorg/ace-builds#70]
I just open the file, and do nothing.The file content is lost when I press 'ctrl-z'.I use the method 'setValue(val, -1)'.Is there something warong?
ace-builds and version: 1.2.0

**Comment by nightwing** [comment]
editor.setValue calls are included in undo history
use editor.session.setValue if you want to disable undo

**Comment by StriverBoy** [comment]
@nightwing Great! Thanks!!!
