### ISSUE TITLE
Validation and error checking isn't working.

### ISSUE THREAD

**Issue by jlem** [ajaxorg/ace-builds#76]
I followed this embedding guide:

https://ace.c9.io/#nav=embedding

And then replaced the reference to ace.js with the cdnjs version: `https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js`

My total code configuration looked like this:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor-panel");
    editor.setTheme("ace/theme/tomorrow");
    editor.getSession().setMode("ace/mode/javascript");
</script>
```

And that worked fine.

Then I replaced the script source with a locally hosted ace.js build from here:

https://github.com/ajaxorg/ace-builds/tree/v1.2.2/src-noconflict

So now my markup looks like this:
```html
<script src="/js/vendor/ace/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor-panel");
    editor.setTheme("ace/theme/tomorrow");
    editor.getSession().setMode("ace/mode/javascript");
</script>
```

But now validation and error checking does not work. Everything else is fine, but not validation/error checking.

Is there something wrong with the build version I used? Why would CDNJS version work, but not the build version from github?

**Comment by nightwing** [comment]
Did you copy worker-* and mode-* files too?

**Comment by jlem** [comment]
Yes and no.

I didn't do that with the CDNJS version, yet it worked fine there. I literally only had the ace.js cdnjs file, and it was working fine.

I did try copying the appropriate worker and mode files for the build version, but when I did that, I was getting errors about `require` and `define` not being defined in my browser.

**Comment by nightwing** [comment]
ace.js loads other files when needed so you do not need to include `<script>` tags for them, but you need alll the files in [src-noconflict](https://github.com/ajaxorg/ace-builds/tree/master/src-noconflict) to be in the same folder as ace.js

**Comment by jlem** [comment]
Oh ok, I understand now. I may have not included the appropriate file in my bowerCopy, I'll double check.

**Comment by jlem** [comment]
This fixed it. Thanks @nightwing
