### ISSUE TITLE
whats the minimum needed for embedding?

### ISSUE THREAD

**Issue by dcsan** [ajaxorg/ace-builds#77]
the docs say i need to add *all* the files in the src/  directory, 
yet the demo seems to only include one file `src-noconflict/ace.js`

https://github.com/ajaxorg/ace-builds/blob/master/editor.html#L31

do i really need to throw everything into my public dir? is there some extra loading going on with ajax beyond the script tag?

however, themes aren't working for me.

```
<script src="src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/twilight");
    editor.session.setMode("ace/mode/javascript");
</script>
```

https://github.com/ajaxorg/ace-builds/blob/master/editor.html#L34

**Comment by nightwing** [comment]
Minimum is ace.js file, which includes textmate theme, and plain text mode.
For other modes you need `mode-<modename>.js` and for themes `theme-<themename>.js` files

Ace loads these files when needed.
