### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by tsneed290** [ajaxorg/ace-builds#85]
Was wondering what the release schedule looks like for this project. We use this project via [brace](https://github.com/thlorenz/brace) (we bundle our project with Browserify), which itself relies on ace-builds to make it Browserify-compatible.

It looks like the last "release" was on 1/17/16, and we would like to make use of a fix that went in to define globals for JSHint in the javascript work back in [March](https://github.com/ajaxorg/ace/commit/3d18b6a3b8db957b34bc5e7d6550885edff1a1b9).

Thank you for your time.

-T

**Comment by nightwing** [comment]
Usually we are releasing a new version once a month or two depending of amount of changes. 
Unfortunately this release got delayed due to some unforeseen issues, but i have pushed v1.2.4 release just now, and next releases won't be delayed.

**Comment by tsneed290** [comment]
Thanks!
