### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by DavidSichau** [ajaxorg/ace-builds#88]
Can you push the latest version 1.2.4 to npm. At the moment only version 1.2.2 is available.

**Comment by Canopee** [comment]
Bonjour,
Après 7 riches années passées au sein de l’agence Canopée, j’ai décidé de prendre mon envol pour une autre destination professionnelle.
C’était un plaisir de collaborer ensemble durant ces années au sein de l’agence. L’équipe de Canopée prend bien sûr le relai pour poursuivre l’aventure.
Pour toutes vos questions techniques, de maintenance et de suivi de dossier, vous pouvez maintenant vous adresser à Coline Ducasse.
Elle est joignable par téléphone  04 90 98 79 39 ou à l'adresse coline.ducasse@canopee.cc

Je vous souhaite de passer une agréable journée.
Bien cordialement

Alexis Esteves

**Comment by nightwing** [comment]
Which package do you use, ace-builds is not published to npm

**Comment by DavidSichau** [comment]
The following package:

https://www.npmjs.com/package/ace-builds

**Comment by Kagami** [comment]
@basicer published it.
I think he should add ajaxorg members to owners of npm package and newest ace build should be published there. It's rather easy to do and published packages are convenient to use with npm. Though it's also perfectly possible to install ace builds via git now:
```json
"dependencies": {
  "ace-builds": "github:ajaxorg/ace-builds#v1.2.5"
}
```

**Comment by basicer** [comment]
I updated npm.  My deployment script was having worlds of problems with linking it via github, so the easiest solution for me at the time was just to type `npm publish`.  If the maintainers would rather be in charge or keeping npm up to date, I'll happily give the package to them.

**Comment by 304NotModified** [comment]
Is https://www.npmjs.com/package/ace-builds the official one? There is also a https://www.npmjs.com/package/ace-editor-builds ...

**Comment by nightwing** [comment]
https://www.npmjs.com/package/ace-builds is the official one, https://github.com/ajaxorg/ace-builds/pull/112 added a badge for it
