### ISSUE TITLE
After write HTML comments, editor not saved content

### ISSUE THREAD

**Issue by dimti** [ajaxorg/ace-builds#90]
I use ace-builds for wysiwyg reasons on my CMS

Ace work ok, and i setting for ace to updated textarea field on every change in editor area.
But, if i wrote html comment in ace editor <!-- my textarea clearing and after save page on my CMS - i fetched empty page without any content.

It strange, when if i save content with html comments (not write in current session) - save is works.

Build v1.2.5

**Comment by nightwing** [comment]
sounds like a bug with escaping html. if you use editor.setValue(text) and text=editor.getValue() methods text string doesn't change except for normalizing line endings.

**Comment by dimti** [comment]
Yes. Problem with escaping html data is exists. Our resolved that problem with move connected textarea element long long after ace-editor container.
And i have problem with javascript tags in ace-editor and renderer that tags on web-page (loading javascript after render html from ace editor).
All is problems solved. <script> tags i stripped before render html. Thanks for the feedback
