### ISSUE TITLE
Chinese input fail to work on the latest Chrome version 53

### ISSUE THREAD

**Issue by vikyd** [ajaxorg/ace-builds#92]
Ref:
https://github.com/ajaxorg/ace/issues/3027

Inside Ref, solution:
https://github.com/openatx/atx-webide/commit/69b478a8100789821db4164b2fb0982f9a4c0eb1

How about make change to this respo ?
@nightwing

**Comment by iamwelk** [comment]
https://github.com/ajaxorg/ace/pull/3116

**Comment by Viky-zhang** [comment]
@iamwelk  
I am using bower, so I want to use this project instead of https://github.com/ajaxorg/ace, but this project not fixed yet.

**Comment by iamwelk** [comment]
@Viky-zhang 
you can try to add the code to your file after has downloaded, maybe it will work.

**Comment by Viky-zhang** [comment]
@iamwelk  
I add that code and it works several days ago.  And works!
But modify libs  from bower install maybe not a good practice.

**Comment by iamwelk** [comment]
@Viky-zhang haha, it depends on the owner. I am just a passing by
