### ISSUE TITLE
Publish 1.2.6 to NPM

### ISSUE THREAD

**Issue by pawelpabich** [ajaxorg/ace-builds#96]
Hi,

Can you please publish 1.2.6 to npm? At the moment it says 1.2.5 is the highest available version.

Thanks!

**Comment by nightwing** [comment]
@basicer i see you have created https://www.npmjs.com/package/ace-builds package on npm, could you add https://www.npmjs.com/~nightwing as a collaborator?

**Comment by ClemMakesApps** [comment]
I would also appreciate it if npm was updated 👍

**Comment by basicer** [comment]
@nightwing I added you.

**Comment by basicer** [comment]
npm should also now be updated =)

**Comment by nightwing** [comment]
Thank you @basicer. I'll add npm publish to the build script to automatically publish 1.2.7 next time
