### ISSUE TITLE
Ace Editor Scrolling throws Cannot read property 'getTokens' of null

### ISSUE THREAD

**Issue by raghuramv1988** [ajaxorg/ace-builds#98]
Steps to reproduce the issue:

1. Initialize ace editor on the browser ( I have a content of about 40 + lines stored in database). Using a chrome developer console docked below the UI brings the scroll bar into play. Here the scrolling works fine.
2. Call destroy editor.
3. Relaunch the editor again.
4. Now scrolling caused the said error

Uncaught TypeError: Cannot read property 'getTokens' of null
    at EditSession.getTokens (ace.js:8729)
    at Text.$renderLine (ace.js:14475)
    at Text.$renderLinesFragment (ace.js:14282)
    at Text.scrollLines (ace.js:14251)
    at VirtualRenderer.$renderChanges (ace.js:16096)
    at ace.js:14957

On further investigation found that the bgTokenizer gets set to null under one of the below two conditions (ace.js - lines 14250 - 14261)

if (config.firstRow < oldConfig.firstRow) {
            var fragment = this.$renderLinesFragment(config, config.firstRow, oldConfig.firstRow - 1);
            if (el.firstChild)
                el.insertBefore(fragment, el.firstChild);
            else
                el.appendChild(fragment);
}

if (config.lastRow > oldConfig.lastRow) {
            var fragment = this.$renderLinesFragment(config, oldConfig.lastRow + 1, config.lastRow);
            el.appendChild(fragment);
}

Ace Versions: 1.2.3 and 1.2.6 are two versions where I have observed this error

**Comment by nightwing** [comment]
after destroying the editor, you need to remove its container.

**Comment by raghuramv1988** [comment]
Worked. Thank you for the input.
